In [24]:
import RSCD
import fspbenchmark
import numpy as np

In [25]:
# Load instances
ruiz_small = fspbenchmark.small_instance(100)
print(ruiz_small[0])

[[ 2  2]
 [72 81]
 [77 56]
 [21 56]
 [90 44]
 [97 28]
 [29 47]
 [63 47]
 [98  4]
 [86 99]
 [68 32]]


In [26]:
# solve a HFSP with SA 
ins = ruiz_small[0]
jobs, stages = ins.shape
hfsp = RSCD.HFSP(stages, jobs-1, ins[1:], ins[0])
hfsp.SA(3, 0.95, 10000, 10, 50) #Initial temperature 3, annealing rate 0.95, iterations 10000, step length 10, stop if no improvement after 50 iterations
# the output is following
# for example, [6, 0, 0, 0] means the 7th job processed on the first machine of stage 1 at time 0.
# The last array shows the processing sequence of the solution and total makespan
# Here the solution sequence is decoded using first in first out principle, and each job is assigned to the first available machine at each stage

[[6, 0, 0, 0],
 [0, 0, 1, 0],
 [6, 1, 0, 63],
 [3, 0, 0, 63],
 [0, 1, 1, 72],
 [1, 0, 1, 72],
 [5, 0, 1, 149],
 [3, 1, 0, 153],
 [1, 1, 1, 153],
 [9, 0, 0, 153],
 [8, 0, 1, 178],
 [5, 1, 0, 197],
 [9, 1, 1, 221],
 [2, 0, 0, 221],
 [4, 0, 0, 242],
 [2, 1, 1, 253],
 [8, 1, 0, 264],
 [7, 0, 1, 264],
 [4, 1, 1, 339],
 [7, 1, 0, 363],
 [6, 0, 3, 1, 5, 9, 8, 2, 4, 7, 367]]

In [27]:
# Solve using NEH
# Note that NEH only gives a solution sequence, and 
# the solution sequence is decoded using first in first out principle, and each job is assigned to the first available machine at each stage
hfsp.NEH()

[[5, 0, 0, 0],
 [2, 0, 1, 0],
 [2, 1, 1, 21],
 [9, 0, 1, 21],
 [5, 1, 0, 29],
 [6, 0, 0, 29],
 [9, 1, 0, 89],
 [0, 0, 1, 89],
 [6, 1, 1, 92],
 [8, 0, 0, 92],
 [0, 1, 0, 161],
 [1, 0, 1, 161],
 [8, 1, 1, 178],
 [3, 0, 0, 178],
 [4, 0, 1, 238],
 [1, 1, 0, 242],
 [7, 0, 0, 268],
 [3, 1, 1, 277],
 [4, 1, 0, 335],
 [7, 1, 1, 366],
 [5, 2, 9, 6, 0, 8, 1, 3, 4, 7, 370]]

In [28]:
# Use rper to show the information of the instance
hfsp.rper(0)

# Above solution information is not stored in the instance, and we can use following function
hfsp.solve('NEH')
#or
#hfsp.solve_SA(3, 0.95, 10000, 10, 50)
# Then
hfsp.rper(0)
#use rper(1) also prints processing time matrix

This problem has 10 jobs and 2 stages.
Numbers of machines in each stage are 2, 2, 
Not solved yet.
This problem has 10 jobs and 2 stages.
Numbers of machines in each stage are 2, 2, 
Current solution is
(  5    0    0    0 )
(  2    0   1    0 )
(  2   1   1  21 )
(  9    0   1  21 )
(  5   1    0  29 )
(  6    0    0  29 )
(  9   1    0  89 )
(   0    0   1  89 )
(  6   1   1  92 )
(  8    0    0  92 )
(   0   1    0 161 )
(  1    0   1 161 )
(  8   1   1 178 )
(  3    0    0 178 )
(  4    0   1 238 )
(  1   1    0 242 )
(  7    0    0 268 )
(  3   1   1 277 )
(  4   1    0 335 )
(  7   1   1 366 )
with makespan 370


In [29]:
# If you want to specify a certain solution, like [0,1,2,3,4,5,6,7,8,9]
hfsp.set_solution([0,1,2,3,4,5,6,7,8,9]) 
hfsp.rper(0)

This problem has 10 jobs and 2 stages.
Numbers of machines in each stage are 2, 2, 
Current solution is
(   0    0    0    0 )
(  1    0   1    0 )
(   0   1    0  72 )
(  2    0    0  72 )
(  1   1   1  77 )
(  3    0   1  77 )
(  4    0    0  93 )
(  2   1   1 133 )
(  3   1    0 167 )
(  5    0   1 167 )
(  4   1   1 190 )
(  6    0    0 190 )
(  7    0   1 196 )
(  5   1    0 211 )
(  6   1   1 253 )
(  8    0    0 253 )
(  7   1    0 294 )
(  9    0   1 294 )
(  8   1    0 339 )
(  9   1   1 362 )
with makespan 438


In [30]:
# Permutation flow shop
ta, ta_solus = fspbenchmark.import_taillard(120)
print(ta[0])
print(ta_solus[0])

[[54 79 16 66 58]
 [83  3 89 58 56]
 [15 11 49 31 20]
 [71 99 15 68 85]
 [77 56 89 78 53]
 [36 70 45 91 35]
 [53 99 60 13 53]
 [38 60 23 59 41]
 [27  5 57 49 69]
 [87 56 64 85 13]
 [76  3  7 85 86]
 [91 61  1  9 72]
 [14 73 63 39  8]
 [29 75 41 41 49]
 [12 47 63 56 47]
 [77 14 47 40 87]
 [32 21 26 54 58]
 [87 86 75 77 18]
 [68  5 77 51 68]
 [94 77 40 31 28]]
[1278   16    2    8   13   10   14    5    3    4   17    6    7   15
    9   18    0    1   12   19   11]


In [37]:
ta_ins = ta[0]
numj = ta_ins.shape[0]
nums = ta_ins.shape[1]

pfsp = RSCD.HFSP(nums, numj, ta_ins, np.ones(nums, dtype=int).tolist())
pfsp.NEH()

[[2, 0, 0, 0],
 [2, 1, 0, 15],
 [16, 0, 0, 15],
 [2, 2, 0, 26],
 [16, 1, 0, 47],
 [8, 0, 0, 47],
 [8, 1, 0, 74],
 [7, 0, 0, 74],
 [2, 3, 0, 75],
 [16, 2, 0, 75],
 [8, 2, 0, 101],
 [2, 4, 0, 106],
 [16, 3, 0, 106],
 [7, 1, 0, 112],
 [14, 0, 0, 112],
 [13, 0, 0, 124],
 [10, 0, 0, 153],
 [16, 4, 0, 160],
 [8, 3, 0, 160],
 [7, 2, 0, 172],
 [14, 1, 0, 172],
 [7, 3, 0, 209],
 [8, 4, 0, 218],
 [14, 2, 0, 219],
 [13, 1, 0, 219],
 [15, 0, 0, 229],
 [14, 3, 0, 282],
 [7, 4, 0, 287],
 [13, 2, 0, 294],
 [10, 1, 0, 294],
 [15, 1, 0, 306],
 [12, 0, 0, 306],
 [12, 1, 0, 320],
 [18, 0, 0, 320],
 [10, 2, 0, 335],
 [14, 4, 0, 338],
 [13, 3, 0, 338],
 [15, 2, 0, 342],
 [10, 3, 0, 379],
 [13, 4, 0, 385],
 [5, 0, 0, 388],
 [12, 2, 0, 393],
 [18, 1, 0, 393],
 [5, 1, 0, 424],
 [3, 0, 0, 424],
 [18, 2, 0, 456],
 [10, 4, 0, 464],
 [15, 3, 0, 464],
 [3, 1, 0, 495],
 [4, 0, 0, 495],
 [12, 3, 0, 504],
 [5, 2, 0, 533],
 [18, 3, 0, 543],
 [15, 4, 0, 550],
 [17, 0, 0, 572],
 [5, 3, 0, 594],
 [3, 2, 0, 594],
 [4, 1, 

In [44]:
pfsp.SA(3,0.95,10000,10,50)

[[8, 0, 0, 0],
 [8, 1, 0, 27],
 [14, 0, 0, 27],
 [8, 2, 0, 32],
 [14, 1, 0, 39],
 [5, 0, 0, 39],
 [18, 0, 0, 75],
 [5, 1, 0, 86],
 [8, 3, 0, 89],
 [14, 2, 0, 89],
 [8, 4, 0, 138],
 [12, 0, 0, 143],
 [14, 3, 0, 152],
 [5, 2, 0, 156],
 [18, 1, 0, 156],
 [16, 0, 0, 157],
 [12, 1, 0, 161],
 [13, 0, 0, 189],
 [18, 2, 0, 201],
 [14, 4, 0, 208],
 [5, 3, 0, 208],
 [7, 0, 0, 218],
 [16, 1, 0, 234],
 [13, 1, 0, 255],
 [3, 0, 0, 256],
 [12, 2, 0, 278],
 [5, 4, 0, 299],
 [18, 3, 0, 299],
 [15, 0, 0, 327],
 [7, 1, 0, 330],
 [16, 2, 0, 341],
 [18, 4, 0, 350],
 [12, 3, 0, 350],
 [13, 2, 0, 367],
 [16, 3, 0, 389],
 [3, 1, 0, 390],
 [2, 0, 0, 404],
 [7, 2, 0, 408],
 [12, 4, 0, 418],
 [17, 0, 0, 419],
 [16, 4, 0, 443],
 [13, 3, 0, 443],
 [7, 3, 0, 484],
 [3, 2, 0, 489],
 [15, 1, 0, 489],
 [13, 4, 0, 501],
 [2, 1, 0, 503],
 [15, 2, 0, 504],
 [0, 0, 0, 506],
 [17, 1, 0, 514],
 [3, 3, 0, 543],
 [7, 4, 0, 550],
 [2, 2, 0, 551],
 [1, 0, 0, 560],
 [17, 2, 0, 600],
 [0, 1, 0, 600],
 [3, 4, 0, 611],
 [15, 3, 0,